### ISSUE TITLE
doesn't work with kernel 4.1.2

### ISSUE THREAD

**Issue by destan** [free5lot/hid-apple-patched#8]
I have installed https://github.com/SicVolo/hid-apple-4.1.2 and then installed this patch, the keyboard didn't worked at all and after rebooting it was restored as intended.

is there any plan to make it work with kernel 4.1.2?

**Comment by free5lot** [comment]
It doesn't seem to be a kernel 4.1.2 problem, it's a conflict with patches from custom SicVolo's repository because both use the same hid-apple kernel module.
You've probably messed up the code from two incompatible projects, it won't work.

What you can do:
1) Wait for SicVolo patches to get to the main stream and wait when I or somebody else will fix my patches to compatible with the updated modified kernel.
2) Or ask kernel maintainers to commit my patch to the mainstream kernel:
https://lkml.org/lkml/2015/5/1/213
and wait for SicVolo or somebody else to update his patches to the updated kernel version.
